### ISSUE TITLE
Basic Installation Instructions?

### ISSUE THREAD

**Issue by Lars1234** [Canop/miaou#15]
You have a very nice vagrant set up available, but that is more for development. Personally, I like to run my stuff as it will be "in production" on a dedicated test VM. Do you have set up instructions on how to run this outside of a development environment?

Specifically, I have encountered issues here:

	Error: Cannot find module '/home/Lars/miaou/node_modules/pg/lib/native/../../build/default/binding'
		at Function.Module._resolveFilename (module.js:331:15)
		at Function.Module._load (module.js:273:25)
		at Module.require (module.js:357:17)
		at require (module.js:373:17)
		at Object.<anonymous> (/home/Lars/miaou/node_modules/pg/lib/native/index.js:17:13)
		at Module._compile (module.js:449:26)
		at Object.Module._extensions..js (module.js:467:10)
		at Module.load (module.js:349:32)
		at Function.Module._load (module.js:305:12)
		at Module.require (module.js:357:17)
		at require (module.js:373:17)

This error occurs after I've run `npm install` and when I run the `./start.sh` script.

**Comment by Canop** [comment]
There's now a complete installation guide: https://github.com/Canop/miaou/blob/master/installation.md
