### ISSUE TITLE
Can't set property 'provider' of undefined

### ISSUE THREAD

**Issue by schas002** [Canop/miaou#63]
When I try to login to miaou on dystroy using Stack Exchange, I get this issue:

## TypeError: Cannot set property 'provider' of undefined

-   at Gunzip.<anonymous> (/redacted/passport-stackexchange.js:38:18)
- -   at emitNone (events.js:72:20)
- - -   at Gunzip.emit (events.js:166:7)
- - - -   at endReadableNT (_stream_readable.js:889:12)
- - - - -   at doNTCallback2 (node.js:430:9)
- - - - - -   at process._tickCallback (node.js:344:17) 

I don't know where to send issues like this, so sub question: where to send issues with miaou on the dystroy server?

**Comment by Canop** [comment]
When you encounter a problem, the best is to raise it in the Miaou room of my server ( https://dystroy.org/miaou/1 ) but there's no problem in writing an issue here (in which case the github bot posts it in the relevant room anyway).

**Comment by Canop** [comment]
It's probably related to 
https://trello.com/c/besaAYcS/309-proper-error-message-for-the-user-when-there-s-no-stackoverflow-account-linked-to-a-stackexchange-login-at-account-creation

Do you have a StackOverflow account ?

**Comment by Canop** [comment]
To reduce (not remove) the risk of another user having this problem, I've renamed the StackExchange login into a StackOverflow one.
